# Dockerized Pipeline for DevSecOps

parameters:
- name: DEVSECOPS_SERVICE_LIST
  type: string
  default: 'SECRET,SCA,SAST,IMAGE,INFRA,DAST'
  
- name: APPLICATION_NAME
  type: string
  default: Sample_Java_Application

- name: SCM_URL
  type: string
  default: https://github.com/evmcoedevsecops/hello-world-spring-boot.git

- name: BRANCH
  type: string
  default: master

- name: TECHNOLOGY
  type: string
  default: Java
  values:
  - Java
  - .Net
  - Python
  - JavaScript

- name: VERSION
  type: number
  default: 8
  values:
  - 8
  - 11

- name: IP_ADDRESS
  type: string
  default: 127.0.0.1

- name: DAST_AUTH_URL
  type: string
  default: https://demo.testfire.net/login.jsp

- name: DAST_USERNAME
  type: string
  default: admin

- name: DAST_PASSWORD
  type: string
  default: admin

- name: DAST_USERNAME_FIELD
  type: string
  default: uid
  
- name: DAST_PASSWORD_FIELD
  type: string
  default: passw

- name: DAST_AUTH_EXCLUDE_URLS
  type: string
  default: http://demo.testfire.net/logout.jsp

- name: DASHBOARD_URL
  type: string
  default: 'http://13.127.184.231:8080'
  



trigger:
- main

resources:
- repo: self

variables:
- name: secret_scan_image
  value: evmcoe/devsecops:secret_scanning

- name: sca_scan_image
  value: evmcoe/devsecops:sca_owasp_dc

- name: sast_scan_image
  value: evmcoe/devsecops:sast_spotbugs

- name: container_scan_image
  value: evmcoe/devsecops:container_scanning_trivy

- name: infra_scan_image
  value: evmcoe/devsecops:infra_scan_nmap
  
- name: dast_scan_image
  value: evmcoe/devsecops:dast_zap

stages:
- stage: CI
  displayName: CI
  jobs:  
  - job: SecurityScan
    displayName: Security Scan
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Docker login
      inputs:
        containerRegistry: 'Docker Hub Service Connection'
        command: 'login'
    - task: CmdLine@2
      displayName: Secret Scan
      condition: contains('${{ parameters.DEVSECOPS_SERVICE_LIST }}', 'SECRET' )
      inputs:
        script: |
          docker run --network host -e branch=${{ parameters.BRANCH }} -e git_url=${{ parameters.SCM_URL }} -e dashboard_url=${{ parameters.DASHBOARD_URL }} ${{ variables.secret_scan_image }}